#!/bin/bash

# ----
# Get the node number from host name
# ----
function getNodeNum()
{
    local _PGDATA=$1
    local _VAL=""
    local _NODE_NUM=0

    for _VAL in ${BACKEND_PGDATA_ARR[@]}; do
        if [ "${_PGDATA}" == "${_VAL}" ]; then
            RTN=${_NODE_NUM}
        fi
        _NODE_NUM=`expr ${_NODE_NUM} + 1`
    done

    if [ "${RTN}" == "" ]; then
        return 1
    else
        return 0
    fi
}

PGHOME=__PGHOME__
PSQL=${PGHOME}/bin/psql
PG_CTL=${PGHOME}/bin/pg_ctl

PG_SUPER_USER=__PG_SUPER_USER__
PGPOOL_LOG_DIR=__PGPOOL_LOG_DIR__
